name       : libcinnamon-desktop
version    : 5.8.0
release    : 4
source     :
    - https://github.com/linuxmint/cinnamon-desktop/archive/refs/tags/5.8.0.tar.gz : 53080bd27527a8271d659e143a8d3b333d9b85efc82b77e571075f9cf8d3287c
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : The cinnamon-desktop library
description: |
    libcinnamon-desktop contains the libcinnamon-desktop library.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
setup      : |
    %patch -p1 < $pkgfiles/0001-Only-compile-the-desktop-library.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
