name       : libcinnamon-desktop
version    : 5.6.0
release    : 2
source     :
    - https://github.com/linuxmint/cinnamon-desktop/archive/refs/tags/5.6.0.tar.gz : d929c449b66d8396140075dcfdac84c63c41affaaeca4d372b017d80835eef90
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : The cinnamon-desktop library
description: |
    libcinnamon-desktop contains the libcinnamon-desktop library.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
setup      : |
    %patch -p1 < $pkgfiles/0001-Only-compile-the-desktop-library.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
