name       : libcinnamon-desktop
version    : 5.6.0
release    : 1
source     :
    - https://github.com/linuxmint/cinnamon-desktop/archive/refs/tags/master.mint21.tar.gz : c8a6ceba4b570cc7037e2da62d49a59c573b7f39c727dc73098f91c9ca930edf
license    : LGPL-2.0-or-later
component  : desktop.library
summary    : The cinnamon-desktop library
description: |
    libcinnamon-desktop contains the libcinnamon-desktop library.
builddeps  :
    - pkgconfig(gtk+-3.0)
    - pkgconfig(xkbfile)
    - pkgconfig(xkeyboard-config)
setup      : |
    %patch -p1 < $pkgfiles/0001-Only-compile-the-desktop-library.patch
    %meson_configure
build      : |
    %ninja_build
install    : |
    %ninja_install
